export const FETCH_DISHES = 'FETCH_DISHES';

export const FETCH_EDIT_DISHES = 'FETCH_EDIT_DISHES';
export const INPUT_CHANGE_HANDLER = 'INPUT_CHANGE_HANDLER';
export const ADD_CHANGES = 'ADD_CHANGES';

export const FETCH_ORDERS = 'FETCH_ORDERS';
export const FETCH_DISHES_PRICE = 'FETCH_DISHES_PRICE';
export const DELETE_ORDER = 'DELETE_ORDER';